# Generated by Django 3.1.1 on 2020-10-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comment_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='signature',
            field=models.CharField(max_length=100),
        ),
    ]
