# Generated by Django 3.1.1 on 2020-10-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201016_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_cat', models.CharField(default='misc', max_length=120)),
            ],
        ),
    ]
